// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//status can be TODO = 0;INPROGRESS = 1;DONE = 2
type Status int32

const (
	Status_UNKNOWN    Status = 0
	Status_TODO       Status = 1
	Status_INPROGRESS Status = 2
	Status_DONE       Status = 3
)

var Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "TODO",
	2: "INPROGRESS",
	3: "DONE",
}

var Status_value = map[string]int32{
	"UNKNOWN":    0,
	"TODO":       1,
	"INPROGRESS": 2,
	"DONE":       3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

//todo item represented by a title, a description and a status
type ToDoItem struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Status               Status   `protobuf:"varint,4,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToDoItem) Reset()         { *m = ToDoItem{} }
func (m *ToDoItem) String() string { return proto.CompactTextString(m) }
func (*ToDoItem) ProtoMessage()    {}
func (*ToDoItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *ToDoItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToDoItem.Unmarshal(m, b)
}
func (m *ToDoItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToDoItem.Marshal(b, m, deterministic)
}
func (m *ToDoItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToDoItem.Merge(m, src)
}
func (m *ToDoItem) XXX_Size() int {
	return xxx_messageInfo_ToDoItem.Size(m)
}
func (m *ToDoItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ToDoItem.DiscardUnknown(m)
}

var xxx_messageInfo_ToDoItem proto.InternalMessageInfo

func (m *ToDoItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ToDoItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ToDoItem) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNKNOWN
}

//AddToDo request message
type AddToDoItem struct {
	ToDoItem             *ToDoItem `protobuf:"bytes,1,opt,name=toDoItem,proto3" json:"toDoItem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddToDoItem) Reset()         { *m = AddToDoItem{} }
func (m *AddToDoItem) String() string { return proto.CompactTextString(m) }
func (*AddToDoItem) ProtoMessage()    {}
func (*AddToDoItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *AddToDoItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToDoItem.Unmarshal(m, b)
}
func (m *AddToDoItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToDoItem.Marshal(b, m, deterministic)
}
func (m *AddToDoItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToDoItem.Merge(m, src)
}
func (m *AddToDoItem) XXX_Size() int {
	return xxx_messageInfo_AddToDoItem.Size(m)
}
func (m *AddToDoItem) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToDoItem.DiscardUnknown(m)
}

var xxx_messageInfo_AddToDoItem proto.InternalMessageInfo

func (m *AddToDoItem) GetToDoItem() *ToDoItem {
	if m != nil {
		return m.ToDoItem
	}
	return nil
}

//toDoItem with hash
type GetToDoItem struct {
	Hash                 string    `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ToDoItem             *ToDoItem `protobuf:"bytes,2,opt,name=toDoItem,proto3" json:"toDoItem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetToDoItem) Reset()         { *m = GetToDoItem{} }
func (m *GetToDoItem) String() string { return proto.CompactTextString(m) }
func (*GetToDoItem) ProtoMessage()    {}
func (*GetToDoItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *GetToDoItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetToDoItem.Unmarshal(m, b)
}
func (m *GetToDoItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetToDoItem.Marshal(b, m, deterministic)
}
func (m *GetToDoItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetToDoItem.Merge(m, src)
}
func (m *GetToDoItem) XXX_Size() int {
	return xxx_messageInfo_GetToDoItem.Size(m)
}
func (m *GetToDoItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GetToDoItem.DiscardUnknown(m)
}

var xxx_messageInfo_GetToDoItem proto.InternalMessageInfo

func (m *GetToDoItem) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *GetToDoItem) GetToDoItem() *ToDoItem {
	if m != nil {
		return m.ToDoItem
	}
	return nil
}

//DeleteToDo request message
type DeleteToDoItem struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteToDoItem) Reset()         { *m = DeleteToDoItem{} }
func (m *DeleteToDoItem) String() string { return proto.CompactTextString(m) }
func (*DeleteToDoItem) ProtoMessage()    {}
func (*DeleteToDoItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *DeleteToDoItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteToDoItem.Unmarshal(m, b)
}
func (m *DeleteToDoItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteToDoItem.Marshal(b, m, deterministic)
}
func (m *DeleteToDoItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteToDoItem.Merge(m, src)
}
func (m *DeleteToDoItem) XXX_Size() int {
	return xxx_messageInfo_DeleteToDoItem.Size(m)
}
func (m *DeleteToDoItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteToDoItem.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteToDoItem proto.InternalMessageInfo

func (m *DeleteToDoItem) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

//UpdateToDo request message
type UpdateToDoItem struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Status               Status   `protobuf:"varint,2,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateToDoItem) Reset()         { *m = UpdateToDoItem{} }
func (m *UpdateToDoItem) String() string { return proto.CompactTextString(m) }
func (*UpdateToDoItem) ProtoMessage()    {}
func (*UpdateToDoItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *UpdateToDoItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateToDoItem.Unmarshal(m, b)
}
func (m *UpdateToDoItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateToDoItem.Marshal(b, m, deterministic)
}
func (m *UpdateToDoItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateToDoItem.Merge(m, src)
}
func (m *UpdateToDoItem) XXX_Size() int {
	return xxx_messageInfo_UpdateToDoItem.Size(m)
}
func (m *UpdateToDoItem) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateToDoItem.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateToDoItem proto.InternalMessageInfo

func (m *UpdateToDoItem) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *UpdateToDoItem) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNKNOWN
}

//GetAllToDo request message
type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

//GetAllToDo response
type AllToDoItems struct {
	ToDoItems            *GetToDoItem     `protobuf:"bytes,1,opt,name=toDoItems,proto3" json:"toDoItems,omitempty"`
	GenericResponse      *GenericResponse `protobuf:"bytes,2,opt,name=genericResponse,proto3" json:"genericResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AllToDoItems) Reset()         { *m = AllToDoItems{} }
func (m *AllToDoItems) String() string { return proto.CompactTextString(m) }
func (*AllToDoItems) ProtoMessage()    {}
func (*AllToDoItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *AllToDoItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllToDoItems.Unmarshal(m, b)
}
func (m *AllToDoItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllToDoItems.Marshal(b, m, deterministic)
}
func (m *AllToDoItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllToDoItems.Merge(m, src)
}
func (m *AllToDoItems) XXX_Size() int {
	return xxx_messageInfo_AllToDoItems.Size(m)
}
func (m *AllToDoItems) XXX_DiscardUnknown() {
	xxx_messageInfo_AllToDoItems.DiscardUnknown(m)
}

var xxx_messageInfo_AllToDoItems proto.InternalMessageInfo

func (m *AllToDoItems) GetToDoItems() *GetToDoItem {
	if m != nil {
		return m.ToDoItems
	}
	return nil
}

func (m *AllToDoItems) GetGenericResponse() *GenericResponse {
	if m != nil {
		return m.GenericResponse
	}
	return nil
}

// this is a generic response to add, put and delete request
type GenericResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericResponse) Reset()         { *m = GenericResponse{} }
func (m *GenericResponse) String() string { return proto.CompactTextString(m) }
func (*GenericResponse) ProtoMessage()    {}
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *GenericResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericResponse.Unmarshal(m, b)
}
func (m *GenericResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericResponse.Marshal(b, m, deterministic)
}
func (m *GenericResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericResponse.Merge(m, src)
}
func (m *GenericResponse) XXX_Size() int {
	return xxx_messageInfo_GenericResponse.Size(m)
}
func (m *GenericResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenericResponse proto.InternalMessageInfo

func (m *GenericResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GenericResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("Status", Status_name, Status_value)
	proto.RegisterType((*ToDoItem)(nil), "ToDoItem")
	proto.RegisterType((*AddToDoItem)(nil), "AddToDoItem")
	proto.RegisterType((*GetToDoItem)(nil), "GetToDoItem")
	proto.RegisterType((*DeleteToDoItem)(nil), "DeleteToDoItem")
	proto.RegisterType((*UpdateToDoItem)(nil), "UpdateToDoItem")
	proto.RegisterType((*EmptyRequest)(nil), "EmptyRequest")
	proto.RegisterType((*AllToDoItems)(nil), "AllToDoItems")
	proto.RegisterType((*GenericResponse)(nil), "GenericResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x5d, 0x8f, 0xd2, 0x40,
	0x14, 0xb5, 0x15, 0xf9, 0xb8, 0xb0, 0xd0, 0x5c, 0x75, 0x43, 0x58, 0x8d, 0xa4, 0x6a, 0xb2, 0xe1,
	0x61, 0x50, 0xf4, 0x45, 0xde, 0x36, 0x0b, 0xc1, 0x8d, 0x9b, 0xd6, 0x14, 0x36, 0x3e, 0x77, 0xe9,
	0x95, 0x6d, 0x52, 0x3a, 0x95, 0x19, 0x48, 0x8c, 0xf1, 0xc5, 0xbf, 0xe0, 0xcf, 0xf2, 0xd1, 0xbf,
	0xe0, 0x0f, 0x31, 0x4c, 0xa7, 0x40, 0x59, 0x76, 0xdf, 0xe6, 0xce, 0xb9, 0x73, 0xe6, 0x9e, 0x39,
	0x67, 0xe0, 0x48, 0xd0, 0x62, 0x15, 0x4e, 0x89, 0x25, 0x0b, 0x2e, 0x79, 0xeb, 0xd9, 0x8c, 0xf3,
	0x59, 0x44, 0x5d, 0x3f, 0x09, 0xbb, 0x7e, 0x1c, 0x73, 0xe9, 0xcb, 0x90, 0xc7, 0x42, 0xa3, 0x27,
	0x1a, 0x55, 0xd5, 0xf5, 0xf2, 0x6b, 0x97, 0xe6, 0x89, 0xfc, 0x9e, 0x82, 0xf6, 0x14, 0xca, 0x13,
	0x3e, 0xe0, 0x17, 0x92, 0xe6, 0xf8, 0x04, 0x1e, 0xc9, 0x50, 0x46, 0xd4, 0x34, 0xda, 0xc6, 0x69,
	0xc5, 0x4b, 0x0b, 0x6c, 0x43, 0x35, 0x20, 0x31, 0x5d, 0x84, 0xc9, 0x9a, 0xb4, 0x69, 0x2a, 0x6c,
	0x77, 0x0b, 0x5f, 0x40, 0x51, 0x48, 0x5f, 0x2e, 0x45, 0xb3, 0xd0, 0x36, 0x4e, 0xeb, 0xbd, 0x12,
	0x1b, 0xab, 0xd2, 0xd3, 0xdb, 0xf6, 0x7b, 0xa8, 0x9e, 0x05, 0xc1, 0xe6, 0x9e, 0xd7, 0x50, 0x96,
	0x7a, 0xad, 0xae, 0xaa, 0xf6, 0x2a, 0x2c, 0x03, 0xbd, 0x0d, 0x64, 0x7f, 0x84, 0xea, 0x88, 0xe4,
	0xe6, 0x14, 0x42, 0xe1, 0xc6, 0x17, 0x37, 0x7a, 0x38, 0xb5, 0xce, 0x31, 0x99, 0x77, 0x33, 0xbd,
	0x82, 0xfa, 0x80, 0x22, 0x92, 0x74, 0x1f, 0x99, 0x3d, 0x84, 0xfa, 0x55, 0x12, 0xf8, 0xf7, 0x77,
	0xed, 0x88, 0x35, 0x0f, 0x8b, 0xad, 0x43, 0x6d, 0xb8, 0x7e, 0x60, 0x8f, 0xbe, 0x2d, 0x49, 0x48,
	0x7b, 0x05, 0xb5, 0xb3, 0x28, 0xca, 0x38, 0x05, 0x76, 0xa0, 0x92, 0x0d, 0x26, 0xb4, 0xfc, 0x1a,
	0xdb, 0x11, 0xea, 0x6d, 0x61, 0xec, 0x43, 0x63, 0x46, 0x31, 0x2d, 0xc2, 0xa9, 0x47, 0x22, 0xe1,
	0xb1, 0x20, 0x2d, 0xd3, 0x62, 0xa3, 0xfc, 0xbe, 0xb7, 0xdf, 0x68, 0x9f, 0x43, 0x63, 0xaf, 0x07,
	0x8f, 0x37, 0xb3, 0xa7, 0x8a, 0x74, 0x85, 0x4d, 0x28, 0xcd, 0x49, 0x08, 0x7f, 0x46, 0xda, 0xde,
	0xac, 0xec, 0x7c, 0x80, 0x62, 0x2a, 0x0f, 0xab, 0x50, 0xba, 0x72, 0x3e, 0x39, 0xee, 0x17, 0xc7,
	0x7a, 0x80, 0x65, 0x28, 0x4c, 0xdc, 0x81, 0x6b, 0x19, 0x58, 0x07, 0xb8, 0x70, 0x3e, 0x7b, 0xee,
	0xc8, 0x1b, 0x8e, 0xc7, 0x96, 0xb9, 0x46, 0x06, 0xae, 0x33, 0xb4, 0x1e, 0xf6, 0xfe, 0x98, 0xd0,
	0x98, 0xf0, 0x80, 0x5f, 0x86, 0x42, 0x8e, 0xd3, 0xb8, 0xe2, 0x39, 0x94, 0x74, 0x10, 0x70, 0x6b,
	0x54, 0xeb, 0x96, 0x18, 0xfb, 0xe4, 0xd7, 0xdf, 0x7f, 0xbf, 0xcd, 0xa7, 0xb6, 0xa5, 0x22, 0x2d,
	0x79, 0xc0, 0xbb, 0xab, 0xb7, 0x5d, 0x3f, 0x08, 0xfa, 0x46, 0x07, 0x2f, 0x01, 0xb6, 0x6e, 0x62,
	0x83, 0xe5, 0xad, 0xbd, 0x9b, 0xad, 0xf3, 0x38, 0xc7, 0xf6, 0x63, 0x6d, 0xe7, 0x4f, 0x9c, 0x00,
	0x6c, 0x5d, 0xc7, 0x06, 0xcb, 0x47, 0xe0, 0x00, 0xdb, 0x4b, 0xc5, 0xf6, 0xbc, 0x75, 0x88, 0xad,
	0x9f, 0xbd, 0xa8, 0x0b, 0x30, 0x22, 0xa9, 0x7d, 0xc7, 0x63, 0x96, 0x7e, 0x41, 0x96, 0x7d, 0x41,
	0xa6, 0x12, 0xd2, 0x3a, 0x62, 0xbb, 0xc9, 0xb0, 0x9b, 0x8a, 0x19, 0x71, 0x4f, 0x75, 0x14, 0xbd,
	0x31, 0xae, 0x8b, 0xea, 0xe8, 0xbb, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x3e, 0x73, 0xee,
	0xfa, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoListServiceClient is the client API for TodoListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoListServiceClient interface {
	AddToDo(ctx context.Context, in *ToDoItem, opts ...grpc.CallOption) (*GenericResponse, error)
	DeleteToDo(ctx context.Context, in *DeleteToDoItem, opts ...grpc.CallOption) (*GenericResponse, error)
	UpdateToDo(ctx context.Context, in *UpdateToDoItem, opts ...grpc.CallOption) (*GenericResponse, error)
	GetAllToDo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (TodoListService_GetAllToDoClient, error)
}

type todoListServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoListServiceClient(cc *grpc.ClientConn) TodoListServiceClient {
	return &todoListServiceClient{cc}
}

func (c *todoListServiceClient) AddToDo(ctx context.Context, in *ToDoItem, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, "/TodoListService/AddToDo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoListServiceClient) DeleteToDo(ctx context.Context, in *DeleteToDoItem, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, "/TodoListService/DeleteToDo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoListServiceClient) UpdateToDo(ctx context.Context, in *UpdateToDoItem, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, "/TodoListService/UpdateToDo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoListServiceClient) GetAllToDo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (TodoListService_GetAllToDoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TodoListService_serviceDesc.Streams[0], "/TodoListService/GetAllToDo", opts...)
	if err != nil {
		return nil, err
	}
	x := &todoListServiceGetAllToDoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TodoListService_GetAllToDoClient interface {
	Recv() (*AllToDoItems, error)
	grpc.ClientStream
}

type todoListServiceGetAllToDoClient struct {
	grpc.ClientStream
}

func (x *todoListServiceGetAllToDoClient) Recv() (*AllToDoItems, error) {
	m := new(AllToDoItems)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TodoListServiceServer is the server API for TodoListService service.
type TodoListServiceServer interface {
	AddToDo(context.Context, *ToDoItem) (*GenericResponse, error)
	DeleteToDo(context.Context, *DeleteToDoItem) (*GenericResponse, error)
	UpdateToDo(context.Context, *UpdateToDoItem) (*GenericResponse, error)
	GetAllToDo(*empty.Empty, TodoListService_GetAllToDoServer) error
}

// UnimplementedTodoListServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTodoListServiceServer struct {
}

func (*UnimplementedTodoListServiceServer) AddToDo(ctx context.Context, req *ToDoItem) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToDo not implemented")
}
func (*UnimplementedTodoListServiceServer) DeleteToDo(ctx context.Context, req *DeleteToDoItem) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteToDo not implemented")
}
func (*UnimplementedTodoListServiceServer) UpdateToDo(ctx context.Context, req *UpdateToDoItem) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateToDo not implemented")
}
func (*UnimplementedTodoListServiceServer) GetAllToDo(req *empty.Empty, srv TodoListService_GetAllToDoServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllToDo not implemented")
}

func RegisterTodoListServiceServer(s *grpc.Server, srv TodoListServiceServer) {
	s.RegisterService(&_TodoListService_serviceDesc, srv)
}

func _TodoListService_AddToDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToDoItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoListServiceServer).AddToDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TodoListService/AddToDo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoListServiceServer).AddToDo(ctx, req.(*ToDoItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoListService_DeleteToDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteToDoItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoListServiceServer).DeleteToDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TodoListService/DeleteToDo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoListServiceServer).DeleteToDo(ctx, req.(*DeleteToDoItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoListService_UpdateToDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateToDoItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoListServiceServer).UpdateToDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TodoListService/UpdateToDo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoListServiceServer).UpdateToDo(ctx, req.(*UpdateToDoItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoListService_GetAllToDo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TodoListServiceServer).GetAllToDo(m, &todoListServiceGetAllToDoServer{stream})
}

type TodoListService_GetAllToDoServer interface {
	Send(*AllToDoItems) error
	grpc.ServerStream
}

type todoListServiceGetAllToDoServer struct {
	grpc.ServerStream
}

func (x *todoListServiceGetAllToDoServer) Send(m *AllToDoItems) error {
	return x.ServerStream.SendMsg(m)
}

var _TodoListService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TodoListService",
	HandlerType: (*TodoListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddToDo",
			Handler:    _TodoListService_AddToDo_Handler,
		},
		{
			MethodName: "DeleteToDo",
			Handler:    _TodoListService_DeleteToDo_Handler,
		},
		{
			MethodName: "UpdateToDo",
			Handler:    _TodoListService_UpdateToDo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllToDo",
			Handler:       _TodoListService_GetAllToDo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
